name: Builds, tests & co

on:
  pull_request:
    branches: [ "main" ]

permissions:
  read-all
  pull-requests: write
  checks: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    outputs:
      build_status: ${{ job.status }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - run: opam install . --deps-only --with-test

      - name: Build OCaml project
        run: opam exec -- dune build

      - name: Run tests
        run: opam exec -- dune runtest

  report_status:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Post status comment
        uses: actions/github-script@v6
        env:
          BUILD_STATUS: ${{ needs.build.outputs.build_status }}
        with:
          script: |
            const github = require('@actions/github');
            const context = github.context;
            const buildStatus = process.env.BUILD_STATUS;
            let commentBody = '';
            let checkConclusion = 'success';

            if (context.payload.pull_request) {
              if (buildStatus === 'success') {
                commentBody = '✅ OCaml build succeeded on Ubuntu!';
                checkConclusion = 'success';
              } else if (buildStatus === 'failure') {
                commentBody = '❌ OCaml build failed on Ubuntu. See the workflow run for details.';
                checkConclusion = 'failure';
              } else {
                commentBody = `🚧 OCaml build status on Ubuntu: ${buildStatus}`;
                checkConclusion = 'neutral';
              }

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: commentBody
              });

              await github.rest.checks.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head_sha: context.payload.pull_request.head.sha,
                name: 'OCaml Build Status (Ubuntu)',
                status: 'completed',
                conclusion: checkConclusion,
                output: {
                  title: 'OCaml Build (Ubuntu)',
                  summary: commentBody,
                },
              });
            } else {
              console.log('Not a pull request, skipping comment and check.');
            }

  # You can keep the other linting jobs as they are
  lint-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      - uses: ocaml/setup-ocaml/lint-doc@v3

  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      - uses: ocaml/setup-ocaml/lint-fmt@v3

  lint-opam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      - uses: ocaml/setup-ocaml/lint-opam@v3
