name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  pull-requests: write
  checks: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ job.status }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-version: '5.0'
          ocaml-compiler: 'ocamlc' # Explicitly specify the compiler
          opam-version: '2.1'
          allow-prerelease-opam: false
          opam-pin: true
          opam-depext: true
          opam-local-packages: '*.opam' # Corrected quoting
          opam-disable-sandboxing: false
          dune-cache: false
          cache-prefix: v1
          github-token: ${{ secrets.GITHUB_TOKEN }} # It's good practice to use the provided token

      - name: Install OPAM dependencies
        run: opam install . menhir --deps-only -y

      - name: Build OCaml project
        id: build_step
        run: dune build

      - name: Run tests
        run: dune runtest

  report_status:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Post status comment
        uses: actions/github-script@v6
        env:
          BUILD_STATUS: ${{ needs.build.outputs.build_status }}
        with:
          script: |
            const github = require('@actions/github');
            const context = github.context;
            const buildStatus = process.env.BUILD_STATUS;
            let commentBody = '';
            let checkConclusion = 'success';

            if (context.payload.pull_request) {
              if (buildStatus === 'success') {
                commentBody = '✅ OCaml build succeeded!';
                checkConclusion = 'success';
              } else if (buildStatus === 'failure') {
                commentBody = '❌ OCaml build failed. See the workflow run for details.';
                checkConclusion = 'failure';
              } else {
                commentBody = `🚧 OCaml build status: ${buildStatus}`;
                checkConclusion = 'neutral';
              }

              if (commentBody) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.pull_request.number,
                  body: commentBody
                });
              }

              await github.rest.checks.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head_sha: context.payload.pull_request.head.sha,
                name: 'OCaml Build Status',
                status: 'completed',
                conclusion: checkConclusion,
                output: {
                  title: 'OCaml Build',
                  summary: commentBody,
                },
              });
            } else {
              console.log('Not a pull request, skipping comment and check.');
            }
